### ISSUE TITLE
Multithreading gets stuck during training

### ISSUE THREAD

**Issue by chaowentao** [YingqianWang/OACC-Net#1]
Hi, buddy. Your work is excellent. When I try to duplicate your code, I find the code gets stuck. I carefully check the  code, finally I find it may be caused by ``while (sum_diff < 0.01 or glass_region == True):`` in the function ``__getitem__`` . When I annotate the line code, the training process is normal. I don't know if my behavior is correct. Please give me some suggestions.  Thx.

**Comment by chaowentao** [comment]
my solution:
```
# before：
files = os.listdir(cfg.trainset_dir) 'utils.py'
# after:
files = os.listdir(cfg.trainset_dir)
files = sorted(files)
```
It may be caused by the operation: ``os.listdir()``. The operation return filenames are not ordinal, which will mismatch the id and filename.

**Comment by YingqianWang** [comment]
Thanks a lot for your report and solution! This bug has been fixed.
