### ISSUE TITLE
请问得到.pfm深度图,每个像素的距离是多少?

### ISSUE THREAD

**Issue by chenyuyi94** [YingqianWang/OACC-Net#2]
很棒的项目,请问得到.pfm深度图,每个像素的距离是多少?有人可以回复我一下吗

**Comment by YingqianWang** [comment]
您好，感谢您对我们工作的关注。算法输出的pfm文件中每个像素的数值代表视差disparity，不同算法之间的评测与比较均在视差图上完成。
