### ISSUE TITLE
Is there a 7*7 Angle resolution pre-training model? 

### ISSUE THREAD

**Issue by 1094004130** [YingqianWang/OACC-Net#3]
Dude, you're doing a great job.  Is there a 7*7 Angle resolution pre-training model?

**Comment by YingqianWang** [comment]
Thanks for your attention to our work. We have not trained an OACC-Net model for 7x7 LFs. We will have a try in the coming future and will drop you a note when our 7x7 model is released.

**Comment by 1094004130** [comment]
Thank you for your prompt reply！
